package co.com.gym.model;

// default package
// Generated 29-abr-2017 19:04:13 by Hibernate Tools 4.3.1.Final

/**
 * TbEstadoPago generated by hbm2java
 */
public class TbEstadoPago implements java.io.Serializable {

	private Integer idTbEstadoPago;
	private TbTipoContrato tbTipoContrato;
	private TbUsuario tbUsuario;
	private String dstipopago;
	private Integer nmactivo;

	public TbEstadoPago() {
	}

	public TbEstadoPago(TbTipoContrato tbTipoContrato, TbUsuario tbUsuario) {
		this.tbTipoContrato = tbTipoContrato;
		this.tbUsuario = tbUsuario;
	}

	public TbEstadoPago(TbTipoContrato tbTipoContrato, TbUsuario tbUsuario, String dstipopago, Integer nmactivo) {
		this.tbTipoContrato = tbTipoContrato;
		this.tbUsuario = tbUsuario;
		this.dstipopago = dstipopago;
		this.nmactivo = nmactivo;
	}

	public Integer getIdTbEstadoPago() {
		return this.idTbEstadoPago;
	}

	public void setIdTbEstadoPago(Integer idTbEstadoPago) {
		this.idTbEstadoPago = idTbEstadoPago;
	}

	public TbTipoContrato getTbTipoContrato() {
		return this.tbTipoContrato;
	}

	public void setTbTipoContrato(TbTipoContrato tbTipoContrato) {
		this.tbTipoContrato = tbTipoContrato;
	}

	public TbUsuario getTbUsuario() {
		return this.tbUsuario;
	}

	public void setTbUsuario(TbUsuario tbUsuario) {
		this.tbUsuario = tbUsuario;
	}

	public String getDstipopago() {
		return this.dstipopago;
	}

	public void setDstipopago(String dstipopago) {
		this.dstipopago = dstipopago;
	}

	public Integer getNmactivo() {
		return this.nmactivo;
	}

	public void setNmactivo(Integer nmactivo) {
		this.nmactivo = nmactivo;
	}

}
