package co.com.gym.model;

// default package
// Generated 29-abr-2017 19:04:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbFechaEnvio generated by hbm2java
 */
public class TbFechaEnvio implements java.io.Serializable {

	private Integer idTbFechaEnvio;
	private Date fefechaenvio;

	public TbFechaEnvio() {
	}

	public TbFechaEnvio(Date fefechaenvio) {
		this.fefechaenvio = fefechaenvio;
	}

	public Integer getIdTbFechaEnvio() {
		return this.idTbFechaEnvio;
	}

	public void setIdTbFechaEnvio(Integer idTbFechaEnvio) {
		this.idTbFechaEnvio = idTbFechaEnvio;
	}

	public Date getFefechaenvio() {
		return this.fefechaenvio;
	}

	public void setFefechaenvio(Date fefechaenvio) {
		this.fefechaenvio = fefechaenvio;
	}

}
