package co.com.gym.model;

// default package
// Generated 29-abr-2017 19:04:13 by Hibernate Tools 4.3.1.Final

/**
 * TbRutinasXTbServicioId generated by hbm2java
 */
public class TbRutinasXTbServicioId implements java.io.Serializable {

	private int tbRutinasIdTbRutinas;
	private int tbServicioIdTbServicio;

	public TbRutinasXTbServicioId() {
	}

	public TbRutinasXTbServicioId(int tbRutinasIdTbRutinas, int tbServicioIdTbServicio) {
		this.tbRutinasIdTbRutinas = tbRutinasIdTbRutinas;
		this.tbServicioIdTbServicio = tbServicioIdTbServicio;
	}

	public int getTbRutinasIdTbRutinas() {
		return this.tbRutinasIdTbRutinas;
	}

	public void setTbRutinasIdTbRutinas(int tbRutinasIdTbRutinas) {
		this.tbRutinasIdTbRutinas = tbRutinasIdTbRutinas;
	}

	public int getTbServicioIdTbServicio() {
		return this.tbServicioIdTbServicio;
	}

	public void setTbServicioIdTbServicio(int tbServicioIdTbServicio) {
		this.tbServicioIdTbServicio = tbServicioIdTbServicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbRutinasXTbServicioId))
			return false;
		TbRutinasXTbServicioId castOther = (TbRutinasXTbServicioId) other;

		return (this.getTbRutinasIdTbRutinas() == castOther.getTbRutinasIdTbRutinas())
				&& (this.getTbServicioIdTbServicio() == castOther.getTbServicioIdTbServicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTbRutinasIdTbRutinas();
		result = 37 * result + this.getTbServicioIdTbServicio();
		return result;
	}

}
