package co.com.gym.model;

// default package
// Generated 29-abr-2017 19:04:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbServicio generated by hbm2java
 */
public class TbServicio implements java.io.Serializable {

	private Integer idTbServicio;
	private String dsnombre;
	private String dsdescripcion;
	private String nmcupolimite;
	private Date feregistro;

	public TbServicio(Integer idTbServicio, String dsnombre, String dsdescripcion, String nmcupolimite,
			Date feregistro) {
		super();
		this.idTbServicio = idTbServicio;
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
		this.nmcupolimite = nmcupolimite;
		this.feregistro = feregistro;
	}

	public TbServicio() {
	}

	public TbServicio(String dsnombre, String dsdescripcion, String nmcupolimite, Date feregistro) {
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
		this.nmcupolimite = nmcupolimite;
		this.feregistro = feregistro;
	}

	public Integer getIdTbServicio() {
		return this.idTbServicio;
	}

	public void setIdTbServicio(Integer idTbServicio) {
		this.idTbServicio = idTbServicio;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}

	public String getNmcupolimite() {
		return this.nmcupolimite;
	}

	public void setNmcupolimite(String nmcupolimite) {
		this.nmcupolimite = nmcupolimite;
	}

	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}


}
