package co.com.gym.model;

// default package
// Generated 29-abr-2017 19:04:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoContrato generated by hbm2java
 */
public class TbTipoContrato implements java.io.Serializable {

	private Integer idTbTipoContrato;
	private String dsdescripcion;
	private Integer nmprecio;
	private Date feregistro;
	private Set tbEstadoPagos = new HashSet(0);

	public TbTipoContrato() {
	}

	public TbTipoContrato(String dsdescripcion, Integer nmprecio, Date feregistro, Set tbEstadoPagos) {
		this.dsdescripcion = dsdescripcion;
		this.nmprecio = nmprecio;
		this.feregistro = feregistro;
		this.tbEstadoPagos = tbEstadoPagos;
	}

	public Integer getIdTbTipoContrato() {
		return this.idTbTipoContrato;
	}

	public void setIdTbTipoContrato(Integer idTbTipoContrato) {
		this.idTbTipoContrato = idTbTipoContrato;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}

	public Integer getNmprecio() {
		return this.nmprecio;
	}

	public void setNmprecio(Integer nmprecio) {
		this.nmprecio = nmprecio;
	}

	public Date getFeregistro() {
		return this.feregistro;
	}

	public void setFeregistro(Date feregistro) {
		this.feregistro = feregistro;
	}

	public Set getTbEstadoPagos() {
		return this.tbEstadoPagos;
	}

	public void setTbEstadoPagos(Set tbEstadoPagos) {
		this.tbEstadoPagos = tbEstadoPagos;
	}

}
